"use client";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Calendar, Clock } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { useTranslation } from "@/lib/i18n";
import { formatDate } from "@/lib/utils";
import type { BlogPost } from "@/lib/types/blog";
import { MediaFallback } from "@/components/ui/media-fallback";
export function RelatedArticles({ posts = [], categoryId }: { posts?: BlogPost[]; categoryId?: string }) { const { t } = useTranslation(); const related = posts.slice(0, 3); if (!related.length) return null; return <Card><CardHeader><CardTitle className="text-lg">{t("news.relatedArticles")}</CardTitle></CardHeader><CardContent className="space-y-4">{related.map((post) => { const image = post.coverImageUrl || post.media?.[0]?.url; const publishedAt = post.publishedAt ? String(post.publishedAt) : ""; return <Link key={post.id} href={`/news/${post.id}`} className="group block cursor-pointer"><div className="flex space-x-4"><div className="relative h-20 w-24 shrink-0 overflow-hidden rounded-lg bg-gray-100">{image ? <Image src={image} alt={t(post.title)} fill sizes="96px" className="object-cover transition-transform duration-300 group-hover:scale-105" /> : <MediaFallback label={t("common.mediaUnavailable")} className="h-full min-h-0" />}</div><div className="min-w-0 flex-1">{post.category?.name ? <Badge variant="secondary" className="mb-1 text-xs">{t(post.category.name)}</Badge> : null}<h4 className="mb-1 line-clamp-2 text-sm font-semibold text-gray-900 transition-colors group-hover:text-primary">{t(post.title)}</h4><div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-sm text-gray-500"><span className="flex items-center"><Calendar className="mr-1 h-3.5 w-3.5" />{publishedAt ? formatDate(publishedAt) : ""}</span><span className="flex items-center"><Clock className="mr-1 h-3.5 w-3.5" />{post.readTimes || 1} {t("common.minutesShort")}</span></div></div></div></Link>; })}<div className="border-t pt-4"><Button variant="outline" className="w-full text-primary" asChild><Link href={categoryId ? `/news?category=${categoryId}` : "/news"}>{categoryId ? t("news.moreFromCategory") : t("news.viewAllArticles")}<ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></CardContent></Card>; }
